train_params:
  max_steps: 100000000
  lr: 0.0002
  lr_meta: 0.0002
  vf_coef: 0.5
  ent_coef: 0.01
  cliprange: 0.1
  gamma: 0.99
  lam: 0.95
  n_steps: 4500
  n_opt_epochs: 3
  batch_size: 4500
  max_grad_norm: 0.5
  n_traj: 3
  n_traj2: 3
  meta_algo: "reptile" # reptile or maml

env_params:
  exp_type: "x"
  exp_const: 0.005
  color: False
  stack: 2
  scale_rew: True

log:
  log_interval: 1
  save_interval: 10