train_params:
  policy: "cnn"
  max_steps: 200000000
  lr: 0.0002
  vf_coef: 0.5
  ent_coef: 0.01
  cliprange: 0.1
  gamma: 0.99
  lam: 0.95
  n_steps: 4500
  n_opt_epochs: 3
  batch_size: 4500
  max_grad_norm: 0.5
  n_envs: 8
  nmixup: 3
  log_interval: 1
  save_interval: 10
  weights_path: null
  adam_stats: "weight_stats"
  weights_choose_eps: 10

env_params:
  exp_type: "x"
  exp_const: 0.005
  color: False
  stack: 4
  scale_rew: True