train_params:
  cnn: "nature"
  weights_path: ["w1.pkl", "w2.pkl", "w3.pkl", "w4.pkl", "w5.pkl"]
  n_envs: 1
  nmixup: 0
  save_interval: 0
  log_interval: 1
  weights_choose_eps: 5

env_params:
  stack: 2
  exp_type: ["x", "obs"]
  exp_const: [0.0, 0.000]
  socket_dir: "tmp/sock"